### ISSUE TITLE
Migrate octokit.NET to the new generated SDK

### ISSUE THREAD

**Issue by Cai1Hsu** [Loongson-neuq/LoongsonNeuq#1]
GitHub 正在迁移到 kiota 构建的 SDK，因此原有的 octokit 将不再积极维护。并且 octokit 不包含 Classroom 相关 API。详细见下文：

> Hey @Cai1Hsu, 
> 
> Thanks for reaching out.  You are correct.  Maintaining this SDK is a manual task, which is > why we've made the[ move to a generated SDK](https://github.blog/news-insights/product-news/our-move-to-generated-sdks/).  You'll find that our new [generated .NET SDK](https://github.com/octokit/dotnet-sdk/tree/main/src/GitHub/Classrooms) has more feature and almost 100% of all GitHub REST APIS.
> 
> While octokit.net is still maintained our focus has shifted to the new approach for exactly > the reason you mentioned above.  
> 
> Going forward our community has been mostly driving the additions of APIs to this SDK while > we've been focused on building out the [other](https://github.com/octokit/dotnet-sdk).
> 
> Please feel free to add the APIs the this SDK or give the newer one a shot.

_Originally posted by @nickfloyd in https://github.com/octokit/octokit.net/issues/2967#issuecomment-2353561680_

# Task list:

- [x] 删除 octokit.NET 引用
- [x] 添加 GitHub.Octokit.SDK 引用
- [x] 重新实现 octokit.NET 相关代码
- [x] 重构已有代码以尽量复用 GitHub.Octokit.SDK 项目
